package test.java.ormbframework.pageObjects;

public interface DealManagementPageElements 
{
	String Deal_Dashboard_CreateDeal_Button = "//*[@type='button'][@title='Create Deal']";
	String Deal_Information_SearchEntity_Text = "//*[@id='title_heading_1']";
	String Deal_Information_SearchBy_DropDown = "//*[@id='multiQueryZoneFilters1']";
	String Deal_Information_Division_DropDown = "//*[@id='division']";
	String Deal_Information_PersonID_TextBox = "//*[@id='personId']";
	String Deal_Information_AccountID_TextBox = "//*[@id='accountId']";
	String Deal_Information_PersonName_TextBox = "//*[@id='custName']";
	String Deal_Information_Search_Button = "//*[@type='button'][@value='Search']";
	String Deal_Information_Broadcast_Button = "//*[@title='Broadcast - Search Entity - row 1']";
	String Deal_Information_DealIdentifier_TextBox = "//*[@id='dealBS_Deal_dealIdentifier']";
	String Deal_Information_DealTypeSearch_Icon = "//*[@id='dealBS_Deal_dealTypeCode_search']";
	String Deal_Information_DealTypeSearch_ExpandFilters_Button = "//*[@id='inlineFilterButton_1']";
	String Deal_Information_DealTypeSearch_DealType_TextBox = "//*[@orafield='dealTypeCd']";
	String Deal_Information_DealTypeSearch_Button = "//*[@id='anTLZ1Refresh']";
	String Deal_Information_DealType_TextBox = "//*[@id='dealBS_Deal_dealTypeCode']";
	String Deal_Information_DealCurrency_DropDown = "//*[@id='dealBS_Deal_currency']";
	String Deal_Information_SimulationType_DropDown = "//*[@id='dealBS_Deal_simulationTypeFlg']";
	String Deal_Information_StartDate_DateField = "//*[@id='dealBS_Deal_startDate']";
	String Deal_Information_PriceSelectionDate_DateField = "//*[@id='dealBS_Deal_priceSelectionDate']";
	String Deal_Information_ReviewFrequency_DropDown = "//*[@id='dealBS_Deal_reviewFrequency']";
	String Deal_Information_DealFrequency_DropDown = "//*[@id='dealBS_Deal_frequencyFlg']";
	String Deal_Information_UsagePeriod_DropDown = "//*[@id='dealBS_Deal_usagePeriodFlg']";
	String Deal_Information_DealDescription_TextBox = "//*[@id='dealBS_Deal_description']";
	String Deal_Information_DealVersionDescription_TextBox = "//*[@id='dealBS_modelDescr']";
	String Deal_Information_SkipReference_CheckBox = "//*[@id='dealBS_Deal_skipReferenceSW']";
	String Deal_Information_SkipQuestionnaire_CheckBox = "//*[@id='dealBS_Deal_skipQuesnSW']";
	String Deal_Information_TemplateDeal_CheckBox = "//*[@id='dealBS_Deal_templateSwitch']";
	String Deal_Information_TNC1_TextBox = "(//*[@name='tcName'])[1]";
	String Deal_Information_TNC1Plus_Icon = "(//*[@class='imgPlus'])[1]";
	String Deal_Information_TNC2_TextBox = "(//*[@name='tcName'])[2]";
	String Deal_Information_TNC2Plus_Icon = "(//*[@class='imgPlus'])[2]";
	String Deal_Information_TNC3_TextBox = "(//*[@name='tcName'])[3]";
	String Deal_Information_Save_Button = "//*[@id='saveButton']";
	String Deal_Information_DealID_TextBox = "//*[@id='dealBS_dealId']";
	String Deal_Information_Next_Button = "//*[@id='nextButton']";
	String Deal_Information_DealInfoSeaction_TextDetails ="//*[@id='set_dealId']";
	String Deal_Information_DealInfoTitle_Label ="//*[@id='ptitle'][contains(text(),'Deal Information')]";
	String Deal_Information_SimulateDeal_Button ="//*[@id='priceSimulation']";
	String Deal_Information_SimulateDeal_OK_Button ="//*[@id='okBtn']";	
	String Deal_Information_DealSimulationSuccessMessage_Label ="//*[contains(text(),'Deal Simulated Successfully')]";
	String Deal_Information_DealStatus_TextDetails ="//*[@orafield='status']";
	String Deal_Information_DealVersionStatus_TextDetails ="//*[@orafield='model/status']";
	String Deal_Information_DealType_TextDetails ="//*[@oralabel='dealTypeCode']/following-sibling::td[@class='oraNormal oraTableLabel']";
	String Deal_Information_DealCurrency_TextDetails ="//*[@orafield='currency']";
	String Deal_Information_SimulationType_TextDetails ="//*[@oralabel='simulationTypeFlg']/following-sibling::td[@orafield='simulationTypeFlg']";
	String Deal_Information_EffectiveStartDate_TextDetails ="//*[@oraerrorelement='effectiveStartDate']";
	String Deal_Information_AcceptanceDate_TextDetails ="//*[@oraerrorelement='acceptanceDate']";
	String Deal_Information_FinalizedDate_TextDetails ="//*[@class='oraNormal oraTableLabel oraDate'][@oraerrorelement='finalizedDate']";
	String Deal_Information_StartDate_TextDetails ="//*[@oralabel='startDate']/following-sibling::td[@orafield='startDate']";
	String Deal_Information_CreationDate_TextDetails ="//*[@oralabel='createdDate']/following-sibling::td[@orafield='createdDate']";
	String Deal_Information_ReviewDate_TextDetails ="//*[@orafield='reviewedDate']";	
	String Deal_Information_AccessGroup_TextDetails ="//*[@oraerrorelement='accessGroup']";
	String Deal_Information_CustomerSegment_TextDetails ="//*[@oraerrorelement='customerSegment']";
	String Deal_Information_ViewAndEditPricing_PencilIcon ="View and Edit Pricing";
	String Deal_Information_ViewAndAssignProposedPriceList_PencilIcon ="View and Assign Proposed PriceList";
	String Deal_Information_ExpandAll_Button ="//*[@id='expandAll']";
	String Deal_Price_Item_Group_Selection_ExpandAll_Button ="//*[@id='expandAll']";
	String Deal_Information_PersonalHierarchyPersonName_Label ="(//tr/td/div[@class='personDataCell']/span)[1]";
	String Deal_Information_PersonalHierarchyDivisionName_Label ="(//*[.//text()='ReplacePersonName']/ancestor::tr/td[3]/div)";
	String Deal_Information_PersonalHierarchyRevenueVariationValue_Label ="(//*[@class='oj-fwk-icon oj-fwk-icon-arrow-n oj-menu-item-end-icon upiconSld']/following-sibling::span)";
	String Deal_Information_PersonalHierarchyProjectedRevenueValue_Label ="(//*[.//text()='ReplacePersonName']/ancestor::tr/td//div[@class='rowDataCell proposedData ellipsis'])[1]";
	String Deal_Information_PersonalHierarchyProjectedCostValue_Label ="(//*[.//text()='ReplacePersonName']/ancestor::tr/td//div[@class='rowDataCell proposedData ellipsis'])[2]";
	String Deal_Information_PersonalHierarchyProjectedProfitValue_Label ="(//*[.//text()='ReplacePersonName']/ancestor::tr/td//div[@class='rowDataCell proposedData ellipsis'])[3]";
	String Deal_Information_PersonalHierarchyProjectedProfitabilityValue_Label ="(//*[.//text()='ReplacePersonName']/ancestor::tr/td//div[@class='rowDataCell proposedData ellipsis'])[4]";
	String Deal_Information_PersonalHierarchyOriginalRevenueValue_Label ="(//*[.//text()='ReplacePersonName']/ancestor::tr/td//div[@class='rowDataCell originalData ellipsis'])[1]";
	String Deal_Information_PersonalHierarchyOriginalCostValue_Label ="(//*[.//text()='ReplacePersonName']/ancestor::tr/td//div[@class='rowDataCell originalData ellipsis'])[2]";
	String Deal_Information_PersonalHierarchyOriginalProfitValue_Label ="(//*[.//text()='ReplacePersonName']/ancestor::tr/td//div[@class='rowDataCell originalData ellipsis'])[3]";
	String Deal_Information_PersonalHierarchyOriginalProfitabilityValue_Label ="(//*[.//text()='ReplacePersonName']/ancestor::tr/td//div[@class='rowDataCell originalData ellipsis'])[4]";
	String Deal_Information_DealFinancialSummary_Label ="//*[@id='financialSummaryDealId']";
	String Deal_Information_DealFinancialSummaryProjectedRevenueValue_Label ="//*[@id='proposedRevenueID_1']";
	String Deal_Information_DealFinancialSummaryProjectedCostValue_Label ="//*[@id='proposedRevenueID_1']/following-sibling::td[@orafield='overallProposedCost']";
	String Deal_Information_DealFinancialSummaryProjectedProfitValue_Label ="//*[@id='proposedProfitabilityAmtID_1']";
	String Deal_Information_DealFinancialSummaryProjectedProfitPercentValue_Label ="//*[@id='proposedProfitabilityID_1']";
	String Deal_Information_DealFinancialSummaryRecommendedRevenueValue_Label ="//*[@id='proposedProfitabilityID_1']/following-sibling::td[@orafield='recmRevenue']";
	String Deal_Information_DealFinancialSummaryRecommendedProfitValue_Label ="//*[@id='proposedProfitabilityID_1']/following-sibling::td[@orafield='recmProfitAmount']";
	String Deal_Information_DealFinancialSummaryRecommendedProfitPercentValue_Label="//*[@id='proposedProfitabilityID_1']/following-sibling::td[@orafield='recmProfitabilityS']";
	String Deal_Information_DealFinancialSummaryOriginalRevenueValue_Label ="//*[@id='proposedProfitabilityID_1']/following-sibling::td[@orafield='revenue']";
	String Deal_Information_DealFinancialSummaryOriginalCostValue_Label ="//*[@id='proposedProfitabilityID_1']/following-sibling::td[@orafield='cost']";
	String Deal_Information_DealFinancialSummaryOriginalProfitValue_Label ="//*[@id='proposedProfitabilityID_1']/following-sibling::td[@orafield='overallProfitabilityAmt']";
	String Deal_Information_DealFinancialSummaryOriginalProfitPercentValue_Label ="//*[@id='proposedProfitabilityID_1']/following-sibling::td[@orafield='overallProfitabilityS']";
	String Deal_Information_DealFinancialSummaryOriginalProfitVariationValue_Label ="//*[@id='proposedProfitabilityID_1']/following-sibling::td[@data-modelid='overallDealProfitabiltyDeviationID']";
	String Deal_Information_PersonalHierarchyAccountNameForAccounts_Label ="(//*[.//text()='ReplaceAccountName']/ancestor::tr/td/div[@class='personDataCell']/span)[1]";
	String Deal_Information_PersonalHierarchyDivisionNameForAccounts_Label ="(//*[.//text()='ReplaceAccountName']/ancestor::tr/td[3]/div)";
	String Deal_Information_PersonalHierarchyProjectedRevenueValueForAccounts_Label ="(//*[.//text()='ReplaceAccountName']/ancestor::tr/td//div[@class='rowDataCell proposedData ellipsis'])[1]";
	String Deal_Information_PersonalHierarchyProjectedCostValueForAccounts_Label ="(//*[.//text()='ReplaceAccountName']/ancestor::tr/td//div[@class='rowDataCell proposedData ellipsis'])[2]";
	String Deal_Information_PersonalHierarchyOriginalRevenueValueForAccounts_Label ="(//*[.//text()='ReplaceAccountName']/ancestor::tr/td//div[@class='rowDataCell originalData ellipsis'])[1]";
	String Deal_Information_PersonalHierarchyOriginalCostValueForAccounts_Label ="(//*[.//text()='ReplaceAccountName']/ancestor::tr/td//div[@class='rowDataCell originalData ellipsis'])[2]";
	String Deal_Information_AdhocRevenueAndCost_Link ="//*[@class='oraZoneHeaderLink colorZoneActionLink'][contains(text(),'Adhoc Revenue and Cost')]";
	String Assign_Prizelist_PriceList_TextBox ="//*[@id='priceListId']";
	String Assign_Prizelist_Priority_TextBox ="//*[@id='sequence']";
	String Assign_Prizelist_EffectiveStartDate_TextBox ="//*[@id='startDateNew']";
	String Assign_Prizelist_Save_Button ="//*[@id='save'][@oramdlabel='SAVE_BTN_LBL']";
	String Assign_Prizelist_Cancel_Button ="//*[@oramdlabel='CANCEL_LBL']";	
	String Assign_Prizelist_SaveAndSelectPriceItemGroup_Button ="//*[@value='Save and Select Price Item Group']";
	String Pricing_And_Commitments_SelectPriceItemGroup_Button ="//*[@id='selectionLbl']";
	String Pricing_And_Commitments_NoDataDisplayedAfterPrizeItemSearch_Button ="//*[@class='oj-table-body-message'][contains(text(),'No data to display.')]";
	String Select_Prize_Item_group_Title_Label ="//*[@oramdlabel='SEL_PRICEITM_GRP_LBL']";
	String Select_Prize_Item_group_Filters_Label ="//*[@oramdlabel='F1_FILTERS_LBL']";
	String Select_Prize_Item_group_AssignmentLevel_Filters_Label ="id='oj-searchselect-filter-assignmentLevel|input'";
	String Select_Prize_Item_group_FilterExpand_Label ="//*[@oramdlabel='F1_FILTERS_LBL']/parent::h1/img";
	String Select_Prize_Item_group_SearchFilters_TextBox ="//*[@id='filter|input']";
	String Select_Prize_Item_group_Clear_SearchFilters ="//*[@id='resetFilter_oj4|text']";
	String Select_Prize_Item_group_SearchFilters_Apply_Button = "//*[@aria-labelledby='filter_oj2|text']";
	String Pricing_And_Commitments_ApprovalStatus_Image = "//*[@data-bind='attr: { \'src\': getStatusSrc(($context.$context?.row.attr.prodMngrtPriceItemApprFlag || $context.row.attr.prodMngrtPriceItemApprFlag === \'Y\'), $context.$context?.row.attr.statusCd || $context.row.attr.statusCd), \'alt\':$context.$context?.row.attr.statusCd || $context.row.attr.statusCd, \'title\':$context.$context?.row.attr.statusCd || $context.row.attr.statusCd}']";
	String Select_Prize_Item_group_PrizeItemCheckBoxAfterSearch_Checkbox ="(//*[@class='demo-treeview-checkbox oj-fwk-icon-checkbox-tristate-unselected'])[3]";
	String Select_Prize_Item_group_PrizeItemSecondCheckBoxAfterSearch_Checkbox ="(//*[@class='demo-treeview-checkbox oj-fwk-icon-checkbox-tristate-unselected'])[4]";
	String Select_Prize_Item_group_PrizeItemThirdCheckBoxAfterSearch_Checkbox ="(//*[@class='demo-treeview-checkbox oj-fwk-icon-checkbox-tristate-unselected'])[5]";
	String Select_Prize_Item_group_PrizeItemSelectedCheckBoxAfterSearch_Checkbox ="(//*[@class='demo-treeview-checkbox oj-fwk-icon-checkbox-tristate-selected'])[3]";
	String Select_Prize_Item_group_PrizeItemSecondSelectedCheckBoxAfterSearch_Checkbox ="(//*[@class='demo-treeview-checkbox oj-fwk-icon-checkbox-tristate-selected'])[4]";
	String Select_Prize_Item_group_PrizeItemThirdSelectedCheckBoxAfterSearch_Checkbox ="(//*[@class='demo-treeview-checkbox oj-fwk-icon-checkbox-tristate-selected'])[5]";
	String Select_Prize_Item_group_NoDatatoDisplayMessage_Label ="(//*[contains(text(),'No data to display.')])[1]";
	String Select_Prize_Item_group_AssignmentLevel_DropDown = "//*[@id='assignmentLevel']/div[2]/span/a";
	String Select_Prize_Item_group_AssignmentLevel_Value_From_DropDown = "//*[@text='ReplacePriceAssignmentValue']";
	String Select_Prize_Item_group_AssignmentLevel_DropDown_Value = "//*[@data-oj-containerid='assignmentLevel']//li//oj-highlight-text[@text='ReplacePriceAssignmentStatus']";
	String Select_Prize_Item_group_SelectAll_Button = "//*[@id='selectAll_oj7|text'][(text()='Select All')]";
	String Select_Prize_Item_group_PrizeItem_CheckBoxList ="(//*[@class='demo-treeview-checkbox oj-fwk-icon-checkbox-tristate-selected'])";
	String Select_Prize_Item_group_SaveAndViewPrizingAndCommitments_Button ="//*[@id='saveView']";
	String Pricing_And_Commitments_Title_HeadingText ="//h1[text()='Pricing and Commitments']";
	String Pricing_And_Commitments_TermsAndConditionsForCorporateBanking_PencilIcon ="(//*[@id='button1|text']/*[@title='Terms And Conditions'])[1]";
	String Mapping_Terms_And_Conditions_Title_HeadingLabel ="//*[@class='oraPageTitle'][contains(text(),'Mapping Terms and Conditions')]";
	String Mapping_Terms_And_Conditions_TermsAndCondition1_TextBox ="//*[@id='termsAndCondition_0']";
	String Mapping_Terms_And_Conditions_TermsAndCondition2_TextBox ="//*[@id='termsAndCondition_1']";
	String Mapping_Terms_And_Conditions_Cancel_Button ="//*[@oramdlabel='CANCEL_LBL']";
	String Pricing_And_Commitments_CorporateBanking_ExpandButton ="//*[@aria-label='Level 1'][@class='oj-component-icon oj-clickable-icon-nocontext oj-rowexpander-expand-icon']";
	String Pricing_And_Commitments_AccountServices_ExpandButton ="(//*[@aria-label='Level 2'])[1]";
	String Pricing_And_Commitments_TermsAndConditionsForAccountServices_PencilIcon ="(//*[@id='button1|text']/*[@title='Terms And Conditions'])[2]";
	String Pricing_And_Commitments_CollapseAll_Button ="//*[@aria-level='3']/following-sibling::div[@id='hrchysec']/oj-button[@id='collapseAll']/button[@aria-labelledby='collapseAll|text']";
	String Pricing_And_Commitments_TermsAndConditionsForFirstPrizeItem_PencilIcon ="(//*[@id='button1|text']/*[@title='Terms And Conditions'])[3]";
	String Pricing_And_Commitments_LowerBack_Button_0 = "(//*[@oramdlabel='BACK_LBL'])[2]";
	String Pricing_And_Commitments_LowerBack_Button =  "(//*[@oramdlabel=\'BACK_LBL\' and @onclick='oraSubmitMap('CANCEL',false); errorText();'])[1]";		//"//*[@id='buttonDiv']/*/*[@oramdlabel='BACK_LBL']";
	String Pricing_And_Commitments_ExpandAll_Button ="//*[text()='Expand All']";
	String Pricing_And_Commitments_CommitmentsAndVolumeForCorporateBanking_Image ="(//*[@id='button1|text']/img[@title='Commitments-Volume'])[1]";
	String Pricing_And_Commitments_CommitmentsAndVolumeForAccountServices_Image ="(//*[@id='button1|text']/img[@title='Commitments-Volume'])[2]";
	String Pricing_And_Commitments_AccountServicesCollapse_Button ="(//a[@class='oj-component-icon oj-clickable-icon-nocontext oj-rowexpander-collapse-icon'][@aria-label='Level 2'])[1]";
	String Pricing_And_Commitments_CommitmentsAndVolumeForReportingAndSwift_Image ="(//*[@id='button1|text']/img[@title='Commitments-Volume'])[3]";
	String Pricing_And_Commitments_ReportingAndSwiftCollapse_Button ="(//a[@class='oj-component-icon oj-clickable-icon-nocontext oj-rowexpander-collapse-icon'][@aria-label='Level 2'])[1]";
	String Pricing_And_Commitments_CommitmentsAndVolumeForReportingAndSwift2_Image ="(//*[@id='button1|text']/img[@title='Commitments-Volume'])[5]";
	String Pricing_And_Commitments_DailyServiceQuantity_TextBox ="//*[@id='dailyServiceQuantityProp_0']";
	String Pricing_And_Commitments_LowerBackServiceQtyScreen_Button ="//*[@id='recommendCom']/following-sibling::input[@oramdlabel='BACK_LBL']";
	String Pricing_And_Commitments_TotalRevenueCorporateBanking_Label ="(//*[@data-bind=''attr':{'title':$parent.isLocalData() == 'DEAL' ? ($context.$context?.row.attr.proposedRevenue || $context.row.attr.proposedRevenue) : ($context.$context?.row.attr.localProposedRevenue || $context.row.attr.localProposedRevenue)}'])[1]";
	String Pricing_And_Commitments_TotalCostCorporateBanking_Label ="(//*[@data-bind=''attr':{'title':$parent.isLocalData() == 'DEAL' ? ($context.$context?.row.attr.proposedCostValue || $context.row.attr.proposedCostValue) : ($context.$context?.row.attr.localProposedCostValue || $context.row.attr.localProposedCostValue)}'])[1]";
	String Pricing_And_Commitments_TotalRevenueAccountServices_Label = "(//*[@data-bind=''attr\':{\'title\':$parent.isLocalData() == \'DEAL\' ? ($context.$context?.row.attr.proposedRevenue || $context.row.attr.proposedRevenue) : ($context.$context?.row.attr.localProposedRevenue || $context.row.attr.localProposedRevenue)}'])[2]";
	String Pricing_And_Commitments_TotalCostAccountServices_Label ="(//*[@data-bind=''attr\':{'title':$parent.isLocalData() == 'DEAL' ? ($context.$context?.row.attr.proposedCostValue || $context.row.attr.proposedCostValue) : ($context.$context?.row.attr.localProposedCostValue || $context.row.attr.localProposedCostValue)}'])[2]";
	String Pricing_And_Commitments_TotalRevenueReportingAndSwift_Label ="(//*[@data-bind=''attr':{'title':$parent.isLocalData() == 'DEAL' ? ($context.$context?.row.attr.proposedRevenue || $context.row.attr.proposedRevenue) : ($context.$context?.row.attr.localProposedRevenue || $context.row.attr.localProposedRevenue)}'])[3]";
	String Pricing_And_Commitments_TotalCostReportingAndSwift_Label ="(//*[@data-bind=''attr':{'title':$parent.isLocalData() == 'DEAL' ? ($context.$context?.row.attr.proposedCostValue || $context.row.attr.proposedCostValue) : ($context.$context?.row.attr.localProposedCostValue || $context.row.attr.localProposedCostValue)}'])[3]";
	String Pricing_And_Commitments_UpperBack_Button ="//*[@id='checkLimit']/following-sibling::input[@id='backLbl']";
	String Adhoc_Revenue_And_Cost_Title_Label ="//*[@class='oraPageTitle'][contains(text(),'Adhoc Revenue and Cost')]";
	String Adhoc_Revenue_And_Cost_Sequence1_TextBox ="//*[@id='sequence_0']";
	String Adhoc_Revenue_And_Cost_Currency1_DropDown ="//*[@id='currency_0']";
	String Adhoc_Revenue_And_Cost_Amount1_TextBox ="//*[@id='amount_0']";
	String Adhoc_Revenue_And_Cost_Division1_DropDown ="//*[@id='division_0']";
	String Adhoc_Revenue_And_Cost_RevenueCostType1_DropDown ="//*[@id='revCstGrpFlg_0']";
	String Adhoc_Revenue_And_Cost_AmountType1_DropDown ="//*[@id='revTypeFlg_0']";
	String Adhoc_Revenue_And_Cost_PlusToAddRow1_Button ="//*[@title='Add - List of Values - row 1']";
	String Adhoc_Revenue_And_Cost_Sequence2_TextBox ="//*[@id='sequence_1']";
	String Adhoc_Revenue_And_Cost_Currency2_DropDown ="//*[@id='currency_1']";
	String Adhoc_Revenue_And_Cost_Amount2_TextBox ="//*[@id='amount_1']";
	String Adhoc_Revenue_And_Cost_PrizeItem2_TextBox ="//*[@id='priceItemCode_1']";
	String Adhoc_Revenue_And_Cost_Division2_DropDown ="//*[@id='division_1']";
	String Adhoc_Revenue_And_Cost_RevenueCostType2_DropDown ="//*[@id='revCstGrpFlg_1']";
	String Adhoc_Revenue_And_Cost_AmountType2_DropDown ="//*[@id='revTypeFlg_1']";
	String Adhoc_Revenue_And_Cost_PlusToAddRow2_Button ="//*[@title='Add - List of Values - row 2']";
	String Adhoc_Revenue_And_Cost_Sequence3_TextBox ="//*[@id='sequence_2']";
	String Adhoc_Revenue_And_Cost_Currency3_DropDown ="//*[@id='currency_2']";
	String Adhoc_Revenue_And_Cost_Amount3_TextBox ="//*[@id='amount_2']";
	String Adhoc_Revenue_And_Cost_Division3_DropDown ="//*[@id='division_2']";
	String Adhoc_Revenue_And_Cost_RevenueCostType3_DropDown ="//*[@id='revCstGrpFlg_2']";
	String Adhoc_Revenue_And_Cost_AmountType3_DropDown ="//*[@id='revTypeFlg_2']";
	String Adhoc_Revenue_And_Cost_PlusToAddRow3_Button ="//*[@title='Add - List of Values - row 3']";
	String Adhoc_Revenue_And_Cost_Sequence4_TextBox ="//*[@id='sequence_3']";
	String Adhoc_Revenue_And_Cost_Currency4_DropDown ="//*[@id='currency_3']";
	String Adhoc_Revenue_And_Cost_Amount4_TextBox ="//*[@id='amount_3']";
	String Adhoc_Revenue_And_Cost_Division4_DropDown ="//*[@id='division_3']";
	String Adhoc_Revenue_And_Cost_RevenueCostType4_DropDown ="//*[@id='revCstGrpFlg_3']";
	String Adhoc_Revenue_And_Cost_AmountType4_DropDown ="//*[@id='revTypeFlg_3']";
	String Adhoc_Revenue_And_Cost_Save_Button ="//*[@id='SAVE_BTN_MP']";	
	String Pricing_And_Commitments_PI_022PrizeItem_Text ="(//*[contains(@title,'PI_022')])[2]";
	String Pricing_And_Commitments_PI_022PrizeItemRateValue_TextBox ="(//*[@id='inputIdCustom'])[3]";
	String Pricing_And_Commitments_PI_033PrizeItem_Text ="(//*[contains(@title,'PI_033')])[2]";
	String Pricing_And_Commitments_PI_033PrizeItemRateValue_TextBox ="(//*[@id='inputIdCustom'])[6]";
	String Pricing_And_Commitments_PI_027PrizeItemRateValue_TextBox ="(//*[@id='inputIdCustom'])[10]";
	String Pricing_And_Commitments_PI_028PrizeItemRateValue_TextBox ="(//*[@id='inputIdCustom'])[12]";
	String Pricing_And_Commitments_PI_031PrizeItemRateValue_TextBox ="(//*[@id='inputIdCustom'])[24]";
	String Pricing_And_Commitments_PrizeItemRateValueAfterSearch_TextBox ="(//*[@id='inputIdCustom'])[1]";
	String Pricing_And_Commitments_PI_022PrizeItemVolumeValue_TextBox ="(//*[@id='inputIdCustom'])[4]";
	String Pricing_And_Commitments_PI_027PrizeItemVolumeValue_TextBox ="(//*[@id='inputIdCustom'])[11]";
	String Pricing_And_Commitments_PI_028PrizeItemVolumeValue_TextBox ="(//*[@id='inputIdCustom'])[13]";
	String Pricing_And_Commitments_PrizeItemVolumeValueAfterSearch_TextBox ="(//*[@id='inputIdCustom'])[2]";
	String Pricing_And_Commitments_PrizeItemVolumeValueAfterSearchForSecondPrizeItem_TextBox ="(//*[@id='inputIdCustom'])[4]";
	String Pricing_And_Commitments_PI_021PrizeItemAddSeasoning_Link ="(//*[@id='dataTd']/span[2])[1]";
	String Pricing_And_Commitments_PI_022PrizeItemAddSeasoning_Link ="(//*[@id='dataTd']/span[2])[7]";
	String Pricing_And_Commitments_PI_033PrizeItemAddSeasoning_Link ="(//*[@id='dataTd']/span[2])[16]";
	String Pricing_And_Commitments_PI_024PrizeItemAddSeasoning_Link ="(//*[@id='button1|text']/a)[27]";
	String Pricing_And_Commitments_Override_Checkbox ="//*[@id='checkboxinput']";
	String Pricing_And_Commitments_StartDate_TextBox ="//*[@id='startDateUpd']";
	String Pricing_And_Commitments_Rate1_TextBox ="//*[@id='valueAmt_0']";
	String Pricing_And_Commitments_Rate2_TextBox ="//*[@id='valueAmt_1']";
	String Pricing_And_Commitments_Rate3_TextBox ="//*[@id='valueAmt_2']";
	String Pricing_And_Commitments_Save_Button ="//*[@id='endOverride']";
	String Pricing_And_Commitments_SaveForPI033_Button ="//*[@id='override']";
	String Pricing_And_Commitments_SelectionOfPrizeItemAfterFilter_CheckBox ="//*[@class='oj-checkboxset-wrapper oj-form-control-container']/*/*[@class='oj-radiocheckbox-icon']";
	String Pricing_And_Commitments_SendPriceItemsForApproval_Button ="//*[@id='sendPriceItemsForApproval']";
	String Pricing_And_Commitments_CheckLimits_Button ="//*[@id='checkLimit']";
	String Pricing_And_Commitments_MessageAferSentPrizeForApproval_Label ="//*[@class='oraLabelCenter oraDefault'][contains(text(),'Price Items Assigned to Price Item Manager Successfully')]";
	String Pricing_And_Commitments_MessageAferCheckLimits_Label ="//*[@class='oraLabelCenter oraDefault'][contains(text(),'Pricing Limits Validated Successfully')]";
	String Pricing_And_Commitments_OKOnDealApprovedMessage_Button ="//*[@oramdlabel='OK_LBL']";
	String Deal_Approval_Dashboard_FirstDealInformation_Link ="(//*[contains(@title,'Navigate to related object for a To Do and drill key values')])[1]";
	String Deal_Approval_Dashboard_FirstDealForNavigationToDealInformation_Link ="(//*[@title='Go To Prospect Hierarchy '])[1]";
	String Deal_Approval_Dashboard_Title_Label ="//*[@id='ptitle'][contains(text(),'Deal Approver Dashboard')]";
	String Deal_Approval_Dashboard_ExpandAll_Button ="//*[@id='inlineFilterButton_3'][@value='Expand Filters']";
	String Deal_Dashboard_ExpandAll_Button ="//*[@id='inlineFilterButton_4'][@value='Expand Filters']";
	String Deal_Approval_Dashboard_DealId_TextBox ="//*[@id='dealId']";
	String Deal_Approval_Dashboard_AssignedToMyRole_CheckBox ="//*[@id='assignedApprovalTask']";
	String Deal_Approval_Dashboard_SearchDealLower_Button ="//*[@id='anTLZ3Refresh']";
	String Deal_Dashboard_SearchDealLower_Button ="//*[@id='anTLZ4Refresh']";
	String Deal_Approval_Dashboard_FirstViewApprovalWorkflow_Button ="(//*[contains(@title,'View Approval Workflow - Search Deal')])[1]";
	String Deal_Approval_Workflow_Title_Label ="//*[@class='oraPageTitle'][contains(text(),'Deal Approval Workflow')]";
	String Deal_Approval_Workflow_DealStatus_Label ="//*[@orafield='status']";
	String Deal_Approval_Workflow_SecondActionTakenValue_Label ="(//*[@orafield='dealApprStatus'])[2]";
	String Deal_Approval_Workflow_SecondToDoRoleValue_Label ="(//*[@orafield='toDoRole'])[2]";
	String Deal_Approval_Workflow_Close_Button ="//*[@oramdlabel='CLOSE_LBL']";
	String Deal_Approval_Workflow_RM1_Label ="//*[contains(text(),'RM1')]";
	String Deal_Approval_Workflow_RM1Image_Label ="//*[contains(text(),'RM1')]/preceding-sibling::*";
	String Pricing_And_Commitments_ApproverList_Label ="//*[@id='dataTd']/*/a[@id='currApproval']";
	String Deal_Information_ReturnToSubmitter_Button ="//*[@id='returnToSubmitter']";
	String Deal_Approval_Return_To_Submitter_Title_Label ="//*[@class='oraPageTitle'][contains(text(),'Deal Approval Return To Submitter')]";
	String Deal_Approval_Return_To_Submitter_DealReturnReason_DropDown ="//*[@id='dealRsnCd']";
	String Deal_Approval_Return_To_Submitter_DealReturnSendDealBackWithApproval_DropDown ="//*[@id='sendWithApprFlg']";
	String Deal_Approval_Return_To_Submitter_DealComments_Textbox ="//*[@id='dealComments']";
	String Deal_Approval_Return_To_Submitter_Save_Button ="//*[@oramdlabel='SAVE_BTN_LBL']";
	String Deal_Approval_Return_To_Submitter_MessageAferSave_Button ="//*[@class='oraLabelCenter oraDefault'][contains(text(),'Deal Returned to Submitter Successfully')]";
	String Deal_Approval_Dashboard_FirstDealInformationPriceItemsAreReturnedFromPriceItemManager1_Link ="(//*[contains(@title,'Navigate to related object for a To Do and drill key values')][contains(text(),'Price Items Are Returned from Price Item Manager 1 Successfully')])[1]";
	String Deal_Information_SendDealForApproval_Button ="//*[@id='sendDealForApproval']";
	String Deal_Information_ConfirmationMessageAferSendDealForApproval_Label ="//*[contains(text(),'All Price Item Configuration not Present at next Level, Do You Wish to Continue?')]";
	String Deal_Information_OKAferSendDealForApproval_Button ="//*[@oramdlabel='OK_LBL']";
	String Deal_Information_MessageAferSendDealForApprovalConfirmation_Label ="//*[contains(text(),'Deal Assigned to next Level Successfully')]";
	String Deal_Approval_Workflow_ThirdActionTakenValue_Label ="(//*[@orafield='dealApprStatus'])[3]";
	String Deal_Approval_Workflow_ThirdToDoRoleValue_Label ="(//*[@orafield='toDoRole'])[3]";
	String Deal_Approval_Workflow_FourthActionTakenValue_Label ="(//*[@orafield='dealApprStatus'])[4]";
	String Deal_Approval_Workflow_FourthToDoRoleValue_Label ="(//*[@orafield='toDoRole'])[4]";	
	String Deal_Approval_Workflow_FifthActionTakenValue_Label ="(//*[@orafield='dealApprStatus'])[5]";
	String Deal_Approval_Workflow_FifthToDoRoleValue_Label ="(//*[@orafield='toDoRole'])[5]";
	String Pricing_And_Commitments_RecommendAfterPrizeItemSearched_link ="(//*[@id='button1|text']/a)[6]";
	String Recommended_Pricing_PageTitle_Label ="//*[@oramdlabel='RECM_PRICING_LBL']";
	String Recommended_Pricing_Recommend_Button ="//*[@id='recommend']";
	String Pricing_And_Commitments_RecommendPrizeOfPrizeItemSearched_TextBox ="//*[@id='inputIdCustom']";
	String Deal_Information_ApproveDeal_Button ="//*[@id='approve']";
	String Deal_Information_FinalizeDeal_Button ="//*[@id='finalize']";
	String Deal_Information_OKAferDealFinalized_Button ="//*[@id='IM_OK']";
	String Deal_Information_AcceptDeal_Button ="//*[@oramdlabel='C1_ACCEPT_DL_LBL']";
	String Deal_Information_Refresh_Button ="//*[@id='IM_REFRESH']";
	String Deal_Acceptance_PageTitle_Label ="//*[@class='oraPageTitle'][contains(text(),'Deal Acceptance')]";
	String Deal_Acceptance_EffectiveStartDate_TextBox ="//*[@id='effectiveStartDate']";
	String Deal_Acceptance_DealComments_TextBox ="//*[@id='dealComments']";
	String Deal_Acceptance_Save_Button ="//*[@oramdlabel='SAVE_BTN_LBL']";
	String Deal_Information_ApplyBack_Button ="//*[@id='applyBack']";
	String Pricing_And_Commitments_SaveAfterChangingRatesOfRecommendation_Button ="//*[@id='save']";
	String Deal_Price_Item_Group_Selection_Save_Button ="//*[@id='save']";

	
	String Deal_Information_Status_Pending_for_Approval = "//*[@oramdlabel='C1_PENDING_APPROVAL_LBL']/parent::span/img";
	String Deal_Information_Status_Approved = "//*[@oramdlabel='C1_APPROVED_LBL']/parent::span/img";
	String Deal_division_Financial_Summary_Status = "(//img[@id='divFinSummaryStatusflg'])[1]";
	String Search_Deal_Section = "(//*[contains(text(),'Search Deal')])[1]";
	String Search_Deal_Expand_Filter_Button = "(//*[@value='Expand Filters'])"; //"//*[.//tr//label[text()='Search By']]/tr//input[@value='Expand Filters']"; //"//*[@onload='setZoneExpandToolTip(this, 'Search Deal')']";  //Updated 13012023
	String Deal_Dashboard_Search_Assign_To_My_Role = "//*[@orafield='assignedApprovalTask']";
	String Deal_Dashboard_SearchDealLower_Button1 = "(//*[@value='Search'])[2]";
	String Deal_Dashboard_Search_Deal_Result_Record = "//span[@title='Go To Prospect Hierarchy ' and contains(text(),'ReplaceDealId')]";
	String Deal_Approval_Workflow_ToDoRoleValue_Label ="(//*[@orafield='toDoRole'])";
	String Deal_Approval_Workflow_ToDoRoleActionTakenValue_Label ="(//*[@orafield='dealApprStatus'])";
	String Deal_Approval_Workflow_Approval_History_Table = "(//*[@id='dealWorkflowTabular']//tbody)";
	String sSequenceApprovalHistoryPath = "(//*[@id=\'dealWorkflowTabular\']//tbody//td[@orafield=\'sequence\'])";
	String sProcessApprovalHistoryPath = "(//*[@id=\'dealWorkflowTabular\']//tbody//td[@orafield=\'workflowLbl\'])";
	String sApprovalTypeApprovalHistoryPath = "(//*[@id=\'dealWorkflowTabular\']//tbody//th[@orafield=\'profileType\'])";
	String sDivisionApprovalHistoryPath = "(//*[@id=\'dealWorkflowTabular\']//tbody//td[@orafield=\'division\'])";
	String sProductApprovalHistoryPath = "(//*[@id=\'dealWorkflowTabular\']//tbody//td[@orafield=\'product\'])";
	String sApprovalLevelApprovalHistoryPath = "(//*[@id=\'dealWorkflowTabular\']//tbody//td[@orafield=\'dealLevel\'])";
	String sToDoRoleApprovalHistoryPath = "(//*[@id=\'dealWorkflowTabular\']//tbody//td[@orafield=\'toDoRole\'])";
	String sUserNameApprovalHistoryPath = "(//*[@id=\'dealWorkflowTabular\']//tbody//td[@orafield=\'approverUserId\'])";
	String sActionTakenApprovalHistoryPath = "(//*[@id=\'dealWorkflowTabular\']//tbody//td[@orafield=\'dealApprStatus\'])";
	String sCreateDateTimeApprovalHistoryPath = "(//*[@id=\'dealWorkflowTabular\']//tbody//td[@orafield=\'creationDateTime\'])";
	String sUpdateDateTimeApprovalHistoryPath = "(//*[@id=\'dealWorkflowTabular\']//tbody//td[@orafield=\'updateDateTime\'])";
	String Deal_Information_Customer_Status_On_Personalhierarchy = "(//*[.//text()='ReplacePersonName']/ancestor::tr/td[2]/div/img)[1]";
	String Deal_Information_Customer_Status_On_Personalhierarchy1 = "(//div[starts-with(@class,'rowDataCell centerAlign')]/img[@class='statusFlag'])[1]";
	String Deal_Information_Deal_Status = "//*[@class='summaryDiv']/label[@orafield='status']";
	String Deal_Information_Deal_Version_Status = "//*[@class='summaryDiv']/label[@orafield='model/status']";
	String Deal_Information_Product_Financial_Summary_On_Pricing_And_Commitment_screen = "//tr/td[@orafield='productCode2' and text()='ReplaceProductName']/parent::tr";
	String Deal_Information_Pricing_And_Commitment_Product_ExpandAll = "(//*[@oramdlabel='C1_PROD_FIN_SUM_DETAILS' and text()='Product Financial Summary']/following-sibling::img)";
	String Deal_Information_Pricing_And_Commitment_Division_Currency_Switch_Toggle = "(//*[@class='oj-switch-thumb'])[1]";
	String Deal_Product_FinancialSummary_Switch_Toggle = "(//*[@class='oj-switch-thumb'])[2]";
	String Deal_Information_Deal_Dashboard_ToDo_on_Table = "(//tbody[@id='dataExplorerTableBody3']/tr/td/a[@scrcd='C1-GotoTDObj']/span[contains(text(),'ReplaceDealId')])[1]";
 	String Deal_Information_Deal_Approver_Dashboard_ToDo_on_Table = "(//tbody[@id='dataExplorerTableBody2']/tr/td/a[@scrcd='C1-GotoTDObj']/span[contains(text(),'ReplaceDealId')])[1]";
	String Deal_Pricing_And_Commitments_Filter_PriceItem_Get_Status_Image = "(//*[.//text()='ReplacePriceItem']/ancestor::tr//div[@class='rowDataCell proposedData centerAlign']/img)";
	String Deal_Information_Pricing_and_Commitments_Level_Expand_Seasonal_Price_Item = "(//*[.//text()='ReplacePriceItem']/ancestor::tr/td[2]//div[@class='divSeasonalArrow'])";
	String Deal_Information_Pricing_and_Commitments_Level_Seasonal_Price_Item_status = "(//*[.//text()='ReplacePriceItem']/following-sibling::tr[@class='oj-table-body-row changedDataRow']//div[@class='rowDataCell proposedData centerAlign']/img)[1]";
	String Deal_Information_Pricing_and_Commitments_Level_Price_Item_Approval = "(//*[.//text()='ReplacePriceItem']/ancestor::tr//div[@class='rowDataCell proposedData ellipsis leftAlign c1CurrApproverLabel'])";
	String Deal_Financial_Summary_Status = "//*[@id='finSummaryStatusflg']";
	String Deal_Division_Financial_Summary_Switch_Toggle = "(//*[@class='oj-switch-thumb'])[1]";
	String Select_Product_From_Product_Financial_Summary = "((//tr/td[@orafield='productCode' and text()='ReplaceProductName'])[3]/parent::tr)";
	String DivisionSectionExpandButton = "//*[@oramdlabel='DEALINFO_TLBL' and @onclick=\'oraExpandCollapseSection(this);renderDivTable(this);']";
	String DivisionProposedRevenuePath = "(//oj-table[@id='tableFinSmryDivi']//tr/td[1]/div)[1]";
	String DivisionProposedCostPath = "(//oj-table[@id='tableFinSmryDivi']//tr/td[2]/div)[1]";
	String DivisionProposedProfitPath = "(//oj-table[@id='tableFinSmryDivi']//tr/td[3]/div)[1]";
	String DivisionProposedProfitabilityPath = "(//oj-table[@id='tableFinSmryDivi']//tr/td[4]/div)[1]";

	String DivisionProposedOGRevenueVariationPath = "(//oj-table[@id=\'tableFinSmryDivi\']//tr/td[5]/div/div/div[2])[1]";
	String DivisionProposedOGProfitVariationPath = "(//oj-table[@id=\'tableFinSmryDivi\']//tr/td[6]/div/div/div[2])[1]";

	String DivisionOriginalRevenuePath = "(//oj-table[@id='tableFinSmryDivi']//tr/td/div[@class='rowDataCell originalData ellipsis'])[1]";
	String DivisionOriginalCostPath = "(//oj-table[@id='tableFinSmryDivi']//tr/td/div[@class='rowDataCell originalData ellipsis'])[2]";
	String DivisionOriginalProfitPath = "(//oj-table[@id='tableFinSmryDivi']//tr/td/div[@class='rowDataCell originalData ellipsis'])[3]";
	String DivisionOriginalProfitabilityPath = "(//oj-table[@id='tableFinSmryDivi']//tr/td/div[@class='rowDataCell originalData ellipsis'])[4]";

	
	String DivisionStandardRevenuePath = "(//oj-table[@id='tableFinSmryDivi']//tr/td/div[@class='rowDataCell standardData ellipsis'])[1]";
	String DivisionStandardCostPath = "(//oj-table[@id='tableFinSmryDivi']//tr/td/div[@class='rowDataCell standardData ellipsis'])[2]";
	String DivisionStandardProfitPath = "(//oj-table[@id='tableFinSmryDivi']//tr/td/div[@class='rowDataCell standardData ellipsis'])[3]";
	String DivisionStandardProfitabilityPath = "(//oj-table[@id='tableFinSmryDivi']//tr/td/div[@class='rowDataCell standardData ellipsis'])[4]";

	
//	String Deal_Division_Financial_Summary_Record = "(//tr/td[@id='divisionId1_3' and text()='INDIA DIVISION'])/parent::tr";
	String Deal_Financial_Summary_Table_Record = "((//td[@orafield='productCode' and @data-modelid='productCd'])/parent::tr[@rowindex='4'])";
	String Deal_Click_On_Customer_Action_Icon = "(//*[@class=\'oj-button-label\']/span[@slot=\'endIcon\'])[1]";
	String Deal_Click_On_Account1_Action_Icon = "(//*[@class=\'oj-button-label\']/span[@slot=\'endIcon\'])[2]";
	String Deal_Select_Prize_Item_group_OnCustomer_Pencil_Icon = "Select Price Item Group Selection";
	String Select_Prize_Item_group_PrizeItem_CheckBox_Selection = "(//*[./div/span/a[text()='ReplacePriceItemName']]//span[@class='demo-treeview-checkbox oj-fwk-icon-checkbox-tristate-unselected'])";
	String Deal_PriceItem_Select_On_Pricing_And_Commitments_Screen = "(//div[@class='pihHyperlink' and @title='ReplacePriceItem'])";
	String Deal_PriceItem_Variable_ErrorMSG_On_Orininal_And_Proposed_Pricing_And_Commitments_Screen = "//*[@id='ERRMSG-TEXT-SPAN']/a[@ojmenu=\'opt\']";
	String Deal_PriceItem_Close_ErrorMSG_On_Pricing_And_Commitments_Screen = "//*[@alt='Close']";
	String Deal_PriceItem_Rate_Input_TextBox_On_Pricing_And_Commitments_Screen = "(//*[.//text()='ReplacePriceItem']/ancestor::tr//td/div[@class='rowDataCell proposedData leftAlign']//input)[1]";
	String Deal_PriceItem_with_Parameter_Rate_HyperLink_Navidation_To_Orininal_Pricing_And_Commitments_Screen4 = "(//*[.//div[text()='ReplacePriceItem'] and .//div[text()='ReplaceParameter']]/td/div[@data-bind='attr:{title:($context.$context?.row.attr.proposedPriceAsgnDescr || $context.row.attr.proposedPriceAsgnDescr)}']//span)[1]";
	String Deal_PriceItem_HyperLink_To_Navigate_Orininal_Pricing_And_Commitments_Screen1 = "(//div[@class='pihHyperlink' and @title='ReplacePriceItem']/ancestor::tr//td/div[@data-bind='attr:{title:($context.$context?.row.attr.proposedPriceAsgnDescr || $context.row.attr.proposedPriceAsgnDescr)}']//span)[1]";
	String Deal_Pricing_screen_Display_Sequense = "(//*[@id='priceCompSequenceNo_0'])[1]";
	String Deal_PriceItem_Not_Editable_FixedErrorMSG_On_Orininal_And_Proposed_Pricing_And_Commitments_Screen = "//div[@id='pricing']/div[@id='nonNegotiableDiv']";
	String Deal_PriceItem_Recommended_Rate_Input_TextBox_On_Pricing_And_Commitments_Screen = "(//*[.//text()='ReplacePriceItem']/ancestor::tr//span[text()='Recommend'])";
	String Deal_Orininal_Pricing_And_Commitments_Screen_Back_Button = "(//*[@oramdlabel='BACK_LBL'])[1]";
	String Deal_Pricing_Screen_Price_Component_Rate_TextBoxs_Path = "(//*[@oraerrorelement='valueAmt' and @data-modelid='valueAmt'])";
	String Deal_Pricing_Recommend_Price_item_link = "//span[text()='Recommend']";
	String Deal_Pricing_And_Commitment_Table_Heading_Text = "//*[@title='Price Item Hierarchy']";
	String Deal_Person_Hierarchy_Switch_Toggle = "//*[@id='switch']//div[@role='switch']";
//	String Deal_Information_PersonalHierarchyOriginalRevenueValue_Label_Division_view = "(//*[@class='localData oj-table-data-cell oj-form-control-inherit']/span)[3]";
//	String Deal_Information_PersonalHierarchyOriginalCostValue_Label_Division_view = "(//*[@class='localData oj-table-data-cell oj-form-control-inherit']/span)[4]";
//	String Deal_Information_PersonalHierarchyProjectedRevenueValue_Label_Division_view = "(//*[@class='localData oj-table-data-cell oj-form-control-inherit']/span)[1]";
//	String Deal_Information_PersonalHierarchyProjectedCostValue_Label_Division_view = "(//*[@class='localData oj-table-data-cell oj-form-control-inherit']/span)[2]";
	String Deal_Information_PersonalHierarchyOriginalRevenueValueForAccounts_Label_Division_view ="(//*[.//text()='ReplaceAccountName']/ancestor::tr/td//div[@class='rowDataCell originalData ellipsis'])[1]";
	String Deal_Information_PersonalHierarchyOriginalCostValueForAccounts_Label_Division_view ="(//*[.//text()='ReplaceAccountName']/ancestor::tr/td//div[@class='rowDataCell originalData ellipsis'])[2]";
	String Deal_Information_PersonalHierarchyProjectedCostValueForAccounts_Label_Division_view ="(//*[.//text()='ReplaceAccountName']/ancestor::tr/td//div[@class='rowDataCell proposedData ellipsis'])[2]";
	String Deal_Information_PersonalHierarchyProjectedRevenueValueForAccounts_Label_Division_view ="(//*[.//text()='ReplaceAccountName']/ancestor::tr/td//div[@class='rowDataCell proposedData ellipsis'])[1]";
	String Deal_Information_Deal_Logs_Cancel_Button ="//*[@oramdlabel='CANCEL_LBL']";	
	String Deal_Information_Deal_Logs_CreationDateTime = "(//*[@orafield='logDateTime'])";
	String Deal_Information_Deal_Logs_Details = "(//*[@orafield='details'])";
	String Deal_Information_Deal_Logs_User = "(//*[@orafield='userId'])";
	String Deal_Information_Deal_Logs_LogType = "(//*[@orafield='description'])";
	String Deal_Information_Deal_Logs_Navigation = "//a[text()='Deal Log']";
	String Deal_Information_ViewAndAssignProposeProduct_PencilIcon ="View and Assign Proposed Product";
	String Product_Enrollment_Title_HeadingText ="//span[text()='Product Enrollment']";
	String Product_Enrollment_All_Proposed_Products = "(//*[@name='proposedProdTbody'])";
	String Product_Enrollment_All_Proposed_Product_Broadcast1 = "(//*[.//td[@orafield='productCode' and text()='ReplaceProductCodeName']]/td/span/img[@id_bk='loadProduct'])";
	String Product_Enrollment_sProposedProduct = "//*[@id='productCode_0']";
	String Product_Enrollment_sProposedProductStartDate = "//*[@id='startDate_0']";
	String Product_Enrollment_sProposedProductEndDate = "//*[@id='endDate1_0']";
	String Product_Enrollment_sProposedProductPriority = "//*[@id='priority_0']";
	String Product_Enrollment_SearchProposeProduct_PencilIcon ="//*[@id='productCode_search_0']";
	String Product_Enrollment_SearchProposeProduct_ExpandFilters_Button = "//*[@id='inlineFilterButton_1']";
	String Product_Enrollment_SearchProposeProduct_TextBox = "//*[@id='productCode']";
	String Product_Enrollment_SearchProposeProduct_SearchButton = "//*[@id='anTLZ1Refresh']";
	String Product_Enrollment_Set_ProductPriority = "//*[@id='priority_0']";
	String Product_Enrollment_Save_Button = "//*[@id='save']";
	String Product_Enrollment_List_Proposed_Product = "(//*[@name='proposedProdTbody']//td[@orafield='productCode'])";
	String Product_Enrollment_Cancel_Button = "//*[@id='CANCEL_BTN_MP']";
	String Product_Enrollment_List_Enrolled_Product = "//*[@id='enrolledProdTbody_0']";
	String Product_Enrollment_sProposedProductService = "//*[@id='serviceCd_0_0']";
	String Product_Enrollment_sProposedProductServiceStartDate = "//*[@id='startDate_0_0']";
	String Product_Enrollment_sProposedProductServiceEndDate = "//*[@id='endDate_0_0']";
	String Product_Enrollment_sProposedProductServiceInclusion = "//*[@id='isIncluded_0_0']";
//	String Deal_Information_Pricing_and_Commitments_Navigate_To_Pricing_For_Single_Price_Item = "//tr[.//td//a[text()='ReplacePriceItem']]/td/span[@data-bind=' event: {click: getPricingForSinglePrice}']";
	String GoToPersonFromCustomer360View = "//*[@title='Go To Person ']";
	String GotoAccount1FromCurrentContext = "//*[@id='oraTableContextContainer']/tbody/tr[2]/td[2]/a";
	String PersonHierarchyApproveStatus = "//*[@id='ojetTable:_hdrCol0_48_3']/img";
	String SimulationDetailsApproveStatusIcon = "/html/body/div[4]/span[11]/img";
	String ProfitVariationPath = "//*[@id='overallDealProfitabiltyDeviationID_1']";
	String DivisionLevelOriginalProfit = "//*[@id='id1_1']/tr/td[13]";
	String RecommendedRevenue = "(//oj-table[@id='tableFinSmry']//td/div[@class='rowDataCell recommendedData ellipsis'])[1]";
	String RecommendedProfitAmount = "(//oj-table[@id='tableFinSmry']//td/div[@class='rowDataCell recommendedData ellipsis'])[3]";
	String RecommendedProfitability = "(//oj-table[@id='tableFinSmry']//td/div[@class='rowDataCell recommendedData ellipsis'])[4]";
	String SearchContractIdOnBillableCharge = "//*[@id='SA_ID']";
	String BillableChargeStartDate = "//*[@id='START_DT']";
	String BillableChargeEndDate = "//*[@id='END_DT']";
	String NavigateToSQDetailsTabInBillableCharge = "//*[@title='SQ Details']";
	String BillableChargeServiceQtyIdentifier = "//*[@id='BCHG_SQ:0$SQI_CD']";
	String BillableChargeServiceQty = "//*[@id='BCHG_SQ:0$SVC_QTY']";
	String NavigateToPricingInfoTabInBillableCharge = "//*[@id='PRICING_INFO_LBL']/table/tbody/tr[2]/td";
	String BillableChargePriceItem = "//*[@id='PRICEITEM_CD']";
	String BillableChargePriceItemParameter1 = "//*[@id='PPC_LINE:0$PRICEITEM_PARM_CD']";
	String BillableChargePriceItemParameterValue1 = "//*[@id='PPC_LINE:0$PRICEITEM_PARM_VAL']";
	String BillableChargeAddPriceItemParameter = "//*[@id='IM_PPC_LINE:0$Grid_addButton']";
	String BillableChargePriceItemParameter2 = "//*[@id='PPC_LINE:1$PRICEITEM_PARM_CD']";
	String BillableChargePriceItemParameterValue2 = "//*[@id='PPC_LINE:1$PRICEITEM_PARM_VAL']";
	String BillableChargeSaveButton = "//*[@id='IM_SAVE']";
	String BillableChargeId = "//*[@id='BILLABLE_CHG_ID']";
	String DivisionLevelProjectedProfitabilityAmt = "(//*[@orafield='proposedProfitabilityAmt'])[2]";
	String OverrideOriginalPricing = "(//*[@type='button' and @value='Save' and @style='display: inline;'])[1]";
	String Deal_Information_ViewAndEditPricing_PencilIcon_Of_Specific_Account = "(//tbody/tr[.//text()='ReplacePersonAccountName']//button/div/span)[2]";
	String Deal_Pricing_And_Commitment_Information_For_Specific_Price_Item = "(//tbody/tr/td[.//text()='ReplacePriceItemName' and following-sibling::td[.//text()='ReplacePriceItemParameter']])[1]";
	
	String Deal_Pricing_And_Commitment_Parameter = "//tbody/tr/td[.//text()='ReplacePriceItemName' and following-sibling::td[.//text()='ReplacePriceItemParameterName']]/following-sibling::td//div[@data-bind=''attr':{'title':$context.$context?.row.attr.priceItemParmCode || $context.row.attr.priceItemParmCode}']";
	String Deal_Pricing_And_Commitment_StartDate = "//tbody/tr/td[.//text()='ReplacePriceItemName' and following-sibling::td[.//text()='ReplacePriceItemParameterName']]/following-sibling::td//div[@data-bind=''attr':{'title':$context.$context?.row.attr.startDate || $context.row.attr.startDate}']";
	String Deal_Pricing_And_Commitment_EndDate = "//tbody/tr/td[.//text()='ReplacePriceItemName' and following-sibling::td[.//text()='ReplacePriceItemParameterName']]/following-sibling::td//div[@data-bind=''attr':{'title':$context.$context?.row.attr.endDate || $context.row.attr.endDate}']";
	String Deal_Pricing_And_Commitment_AveragePrice = "//tbody/tr/td[.//text()='ReplacePriceItemName'and following-sibling::td//div[.//text()='ReplacePriceItemParameterName'] ]/following-sibling::td/div[@data-bind=''attr':{'title':$parent.isLocalData() == 'DEAL' ? ($context.$context?.row.attr.proposedAveragePrice || $context.row.attr.proposedAveragePrice) : ($context.$context?.row.attr.localProposedAveragePrice || $context.row.attr.localProposedAveragePrice)}']";
	String Deal_Pricing_And_Commitment_Cost = "//tbody/tr/td[.//text()='ReplacePriceItemName' and following-sibling::td[.//text()='ReplacePriceItemParameterName']]/following-sibling::td//div[@data-bind=''attr':{'title':$parent.isLocalData() == 'DEAL' ? ($context.$context?.row.attr.proposedCostValue || $context.row.attr.proposedCostValue) : ($context.$context?.row.attr.localProposedCostValue || $context.row.attr.localProposedCostValue)}']";
	String Deal_Pricing_And_Commitment_AssignmentLevel = "//tbody/tr/td[.//text()='ReplacePriceItemName' and following-sibling::td[.//text()='ReplacePriceItemParameterName']]/following-sibling::td//div[@data-bind=''attr':{'title':$context.$context?.row.attr.proposedPriceAssignLevel || $context.row.attr.proposedPriceAssignLevel}']";
	String Deal_Pricing_And_Commitment_PriceList = "//tbody/tr/td[.//text()='ReplacePriceItemName' and following-sibling::td[.//text()='ReplacePriceItemParameterName']]/following-sibling::td//div[@data-bind=''attr':{'title':$context.$context?.row.attr.proposedPriceListInfo ||  $context.row.attr.proposedPriceListInfo}']";
	String Deal_Pricing_And_Commitment_Profit = "//tbody/tr/td[.//text()='ReplacePriceItemName' and following-sibling::td[.//text()='ReplacePriceItemParameterName']]/following-sibling::td//div[@data-bind=''attr':{'title':$parent.isLocalData() == 'DEAL' ? ($context.$context?.row.attr.proposedProfit || $context.row.attr.proposedProfit):($context.$context?.row.attr.localProposedProfit || $context.row.attr.localProposedProfit)}']";
//	String Deal_Pricing_And_Commitment_PricingInformation = "//tbody/tr/td[.//text()='ReplacePriceItemName' and following-sibling::td[.//text()='ReplacePriceItemParameterName']]/following-sibling::td//div[@data-bind=''attr':{'title':$parent.isLocalData() == 'DEAL' ? ($context.$context?.row.attr.proposedCostValue || $context.row.attr.proposedCostValue) : ($context.$context?.row.attr.localProposedCostValue || $context.row.attr.localProposedCostValue)}']";
	String Deal_Pricing_And_Commitment_Profitability = "//tbody/tr/td[.//text()='ReplacePriceItemName' and following-sibling::td[.//text()='ReplacePriceItemParameterName']]/following-sibling::td//div[@data-bind=''attr':{'title':$context.$context?.row.attr.proposedProfitabilityPcent || $context.row.attr.proposedProfitabilityPcent}']";
	String Deal_Pricing_And_Commitment_ProfitVariation = "//tbody/tr/td[.//text()='ReplacePriceItemName' and following-sibling::td[.//text()='ReplacePriceItemParameterName']]/following-sibling::td//div[@data-bind=''attr':{'title':$context.$context?.row.attr.profitVarVsAct || $context.row.attr.profitVarVsAct}']";
	String Deal_Pricing_And_Commitment_Revenue = "//tbody/tr/td[.//text()='ReplacePriceItemName' and following-sibling::td[.//text()='ReplacePriceItemParameterName']]/following-sibling::td//div[@data-bind=''attr':{'title':$parent.isLocalData() == 'DEAL' ? ($context.$context?.row.attr.proposedRevenue || $context.row.attr.proposedRevenue) : ($context.$context?.row.attr.localProposedRevenue || $context.row.attr.localProposedRevenue)}']";
	String Deal_Pricing_And_Commitment_Volume = "//tbody/tr/td[.//text()='ReplacePriceItemName' and following-sibling::td[.//text()='ReplacePriceItemParameterName']]/following-sibling::td//input[@data-bind='textInput: $context.$context?.row.attr.serviceQtyString || $context.row.attr.serviceQtyString, event: {blur: setVolume}, attr:{pid: $context.$context?.row.attr.id || $context.row.attr.id}']";
	String Deal_Pricing_And_Commitment_RevenueVariation = "//tbody/tr/td[.//text()='ReplacePriceItemName' and following-sibling::td[.//text()='ReplacePriceItemParameterName']]/following-sibling::td//div[@data-bind=''attr':{'title':$context.$context?.row.attr.revenueVarVsAct || $context.row.attr.revenueVarVsAct}']";
	String Deal_Pricing_And_Commitment_Approver = "//tbody/tr/td[.//text()='ReplacePriceItemName' and following-sibling::td[.//text()='ReplacePriceItemParameterName']]/following-sibling::td//div[@data-bind=''attr':{'title':$context.$context?.row.attr.c1CurrApprover || $context.row.attr.c1CurrApprover}']";
	String Deal_Pricing_And_Commitment_Status = "//tbody/tr/td[.//text()='ReplacePriceItemName' and following-sibling::td[.//text()='ReplacePriceItemParameterName']]/following-sibling::td//img[@data-bind='attr: { 'src': getStatusSrc(($context.$context?.row.attr.prodMngrtPriceItemApprFlag || $context.row.attr.prodMngrtPriceItemApprFlag === 'Y'), $context.$context?.row.attr.statusCd || $context.row.attr.statusCd), 'alt':$context.$context?.row.attr.statusCd || $context.row.attr.statusCd, 'title':$context.$context?.row.attr.statusCd || $context.row.attr.statusCd}']";

	String Deal_Pricing_And_Commitment_Original_AveragePrice = "//tbody/tr/td[.//text()='ReplacePriceItemName' and following-sibling::td[.//text()='ReplacePriceItemParameterName']]/following-sibling::td//div[@data-bind=''attr':{'title':$parent.isLocalData() == 'DEAL' ? ($context.$context?.row.attr.avgPrice || $context.row.attr.avgPrice) : ($context.$context?.row.attr.localAvgPrice || $context.row.attr.localAvgPrice)}']";
	String Deal_Pricing_And_Commitment_Original_Revenue = "//tbody/tr/td[.//text()='ReplacePriceItemName' and following-sibling::td[.//text()='ReplacePriceItemParameterName']]/following-sibling::td//div[@data-bind=''attr':{'title':$parent.isLocalData() == 'DEAL' ? ($context.$context?.row.attr.revenue || $context.row.attr.revenue) : ($context.$context?.row.attr.localRevenue || $context.row.attr.localRevenue)}']";
	String Deal_Pricing_And_Commitment_Original_Cost = "//tbody/tr/td[.//text()='ReplacePriceItemName' and following-sibling::td[.//text()='ReplacePriceItemParameterName']]/following-sibling::td//div[@data-bind=''attr':{'title':$parent.isLocalData() == 'DEAL' ? ($context.$context?.row.attr.cost || $context.row.attr.cost) : ($context.$context?.row.attr.localCost || $context.row.attr.localCost)}']";
	String Deal_Pricing_And_Commitment_Original_PriceList = "//tbody/tr/td[.//text()='ReplacePriceItemName' and following-sibling::td[.//text()='ReplacePriceItemParameterName']]/following-sibling::td//div[@data-bind=''attr':{'title':$context.$context?.row.attr.priceListInfo || $context.row.attr.priceListInfo}']";
	String Deal_Pricing_And_Commitment_Original_AssignmentLevel = "//tbody/tr/td[.//text()='ReplacePriceItemName' and following-sibling::td[.//text()='ReplacePriceItemParameterName']]/following-sibling::td//div[@data-bind=''attr':{'title':$context.$context?.row.attr.lvlLbl || $context.row.attr.lvlLbl}']";
	
	String Deal_Information_Screen_CompareType_Path = "(//oj-select-single[@id='compareType']//span/a)[1]";
	String Deal_Information_Screen_CompareTypeProposedAndOriginalValuePath = "//oj-highlight-text/span[text()='Proposed and Original']";
	String Deal_Information_CreateDealVersion_Button = "//*[@oramdlabel='CREATENEWMODEL']";
	String Deal_Version_PageTitle_Label = "//*[@class='oraPageTitle'][contains(text(),'Deal Version')]";
	String Deal_Version_Description ="//*[@orafield='modelDescription']";
	String Deal_Version_Creation_Method ="//*[@orafield='dealVerCreFlg']";
	String Deal_Version_Save_Button = "//*[@oramdlabel='SAVE_BTN_LBL']";
	String Deal_Version_Information = "//*[@id='set_modelId']";
	String EnterBillableChargeIdOnBillableChargeScreen = "//*[@id='BILLABLE_CHG_ID']";
	String Deal_Information_PersonalHierarchyDivisionProjectedRevenueValue_Label ="(//*[.//text()='ReplacePersonName']/ancestor::tr/td//div[@class='rowDataCell proposedData ellipsis'])[1]";
	String Deal_Information_PersonalHierarchyDivisionProjectedCostValue_Label ="(//*[.//text()='ReplacePersonName']/ancestor::tr/td//div[@class='rowDataCell proposedData ellipsis'])[2]";
	String Deal_Information_PersonalHierarchyDivisionOriginalRevenueValue_Label ="(//*[.//text()='ReplacePersonName']/ancestor::tr/td//div[@class='rowDataCell originalData ellipsis'])[1]";
	String Deal_Information_PersonalHierarchyDivisionOriginalCostValue_Label = "(//*[.//text()='ReplacePersonName']/ancestor::tr/td//div[@class='rowDataCell originalData ellipsis'])[2]";
	
	String DealSectionExpandButton = "//*[@oramdlabel='DEALINFO_TLBL' and @onclick='oraExpandCollapseSection(this); renderTable();']";

	String Deal_Profit_Variation_Percent = "(//oj-table[@id='tableFinSmry']//td//div[@class='rowDataCell originalData']/div[@class='variationLabel ellipsis'])[1]";
	
	String Deal_Projected_Revenue = "(//oj-table[@id='tableFinSmry']//td[1]/div)[1]";
	String Deal_Projected_cost = "(//oj-table[@id='tableFinSmry']//td[2]/div)[1]";
	String Deal_Projected_Profit = "(//oj-table[@id='tableFinSmry']//td[3]/div)[1]";
	String Deal_Projected_Profitability = "(//oj-table[@id='tableFinSmry']//td[4]/div)[1]";
	
	String Deal_Original_Revenue = "(//oj-table[@id='tableFinSmry']//td[1]/div)[2]";
	String Deal_Original_Cost = "(//oj-table[@id='tableFinSmry']//td[2]/div)[2]";
	String Deal_Original_Profit = "(//oj-table[@id='tableFinSmry']//td[3]/div)[2]";
	String Deal_Original_Profitability = "(//oj-table[@id='tableFinSmry']//td[4]/div)[2]";
	
	String Deal_Standard_Revenue = "(//oj-table[@id='tableFinSmry']//td[1]/div)[3]";
	String Deal_Standard_Cost = "(//oj-table[@id='tableFinSmry']//td[2]/div)[3]";
	String Deal_Standard_Profit = "(//oj-table[@id='tableFinSmry']//td[3]/div)[3]";
	String Deal_Standard_Profitability = "(//oj-table[@id='tableFinSmry']//td[4]/div)[3]";
	
	String Deal_Dashboard_Search_Deal_Lower_Button ="(//*[@value='Search'])[2]";
	String search_Algorithm_TextBox = "//*[@orafield='alg']";
	String Search_Algorithm_Code = "//*[@value='Search']";
	String Algorithm_Description_Navigation_link = "//*[@title='Go To Algorithm ']";
	String Algorithm_Parameter_Value_Field = "//*[text()='ReplaceParameter']/ancestor::td//span/input[@orafield='value']";
	String Algorithm_Save_Button = "//*[@value='Save']";
	String Algorithm_Expand_Link = "//*[@id='expandScrollControl']";
	String Algorithm_parameter_frame_Edit_button_click = "//*[@id='EDIT']";
	String AdminMenuAoption = "//*[@data-menuobj='CI_ADMINMENU']/span[text()='A']";
	String AdminMenuAlgorithmOption = "//*[@data-menuobj='CI_ADMINMENU']/span[text()='Algorithm']";
	String AdminMenuAlgorithmSearchOption = "//*[@data-menuobj='CI_ADMINMENU']/span[text()='Search']";
	
	String ProductSectionExpandButton = "//*[@oramdlabel='DEALINFO_TLBL' and @onclick='oraExpandCollapseSection(this);renderProdDivTable(this);']";
	String ProductNamePath = "//div[text()='ReplaceProductName']/ancestor::tr/td[1]/div"; 
	String ProductDivisionNamePath = "//div[text()='ReplaceProductName']/ancestor::tr/td[2]/div";
	String ProductProposedRevenuePath = "(//div[text()='ReplaceProductName']/ancestor::tr/td/div[starts-with(@class,'rowDataCell proposedData ellipsis')])[1]";
	String ProductProposedCostPath = "(//div[text()='ReplaceProductName']/ancestor::tr/td/div[starts-with(@class,'rowDataCell proposedData ellipsis')])[2]";
	String ProductProposedProfitPath = "(//div[text()='ReplaceProductName']/ancestor::tr/td/div[starts-with(@class,'rowDataCell proposedData ellipsis')])[3]";
	String ProductProposedProfitabilityPath = "(//div[text()='ReplaceProductName']/ancestor::tr/td/div[starts-with(@class,'rowDataCell proposedData ellipsis')])[4]";

	String ProductOriginalRevenuePath = "(//div[text()='ReplaceProductName']/ancestor::tr/td/div[starts-with(@class,'rowDataCell originalData ellipsis')])[1]";
	String ProductOriginalCostPath = "(//div[text()='ReplaceProductName']/ancestor::tr/td/div[starts-with(@class,'rowDataCell originalData ellipsis')])[2]";
	String ProductOriginalProfitPath = "(//div[text()='ReplaceProductName']/ancestor::tr/td/div[starts-with(@class,'rowDataCell originalData ellipsis')])[3]";
	String ProductOriginalProfitabilityPath = "(//div[text()='ReplaceProductName']/ancestor::tr/td/div[starts-with(@class,'rowDataCell originalData ellipsis')])[4]";

	String ProductStandardRevenuePath = "(//div[text()='ReplaceProductName']/ancestor::tr/td/div[starts-with(@class,'rowDataCell standardData ellipsis')])[1]";
	String ProductStandardCostPath = "(//div[text()='ReplaceProductName']/ancestor::tr/td/div[starts-with(@class,'rowDataCell standardData ellipsis')])[2]";
	String ProductStandardProfitPath = "(//div[text()='ReplaceProductName']/ancestor::tr/td/div[starts-with(@class,'rowDataCell standardData ellipsis')])[3]";
	String ProductStandardProfitabilityPath = "(//div[text()='ReplaceProductName']/ancestor::tr/td/div[starts-with(@class,'rowDataCell standardData ellipsis')])[4]";

	
	
	
}
